name: npm test

on: 
  workflow_dispatch:
               
jobs:
  jobDemarrage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name : checkOutCode

    - uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - run: npm install 
          # TO COMPLETE
  jobNPMTest: 
    needs: jobDemarrage 
    runs-on: ubuntu-latest
    
    steps:
      
    - uses: actions/checkout@v3
      name : testNPM
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install 
    - run: npm test 

#$GITHUB_WORKSPACE